#!/usr/bin/env sh

echo "------------------------------------------------------------------------"
echo ""
echo "This makefile provides the following targets:"
echo ""
echo "help"
echo "    prints list of all targets (default target)"
echo "dev"
echo "    install/upgrade all tools and dependencies for local development"
echo "docs"
echo "    builds all documentation"
echo "lint"
echo "    runs linter tool to check for problems"
echo "publish"
echo "    publishes a new version of package to PyPI"
echo "test"
echo "    runs all tests in different environments using tox"
echo ""
echo "------------------------------------------------------------------------"